# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'specest_window.ui'
#
# Created: Tue Nov 29 19:29:16 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.Qwt5 import QwtPlot, QwtCounter
import PyQt4.Qt as Qt

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1236, 751)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Spectrum Estimation GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 451))
        self.frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame.setMouseTracking(False)
        self.frame.setAcceptDrops(False)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.sink = QtGui.QVBoxLayout()
        self.sink.setObjectName(_fromUtf8("sink"))
        self.plot = QwtPlot(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.plot.setPalette(palette)
        self.plot.setObjectName(_fromUtf8("plot"))
        self.sink.addWidget(self.plot)
        self.verticalLayout_4.addLayout(self.sink)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 231))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 231))
        self.frame_2.setBaseSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 9)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridGroupBox_2 = QtGui.QGroupBox(self.frame_2)
        self.gridGroupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Input Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.gridGroupBox_2.setObjectName(_fromUtf8("gridGroupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridGroupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget_2 = QtGui.QTabWidget(self.gridGroupBox_2)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_8 = QtGui.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tab_8.setPalette(palette)
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_8)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea_4 = QtGui.QScrollArea(self.tab_8)
        self.scrollArea_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 374, 155))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.formLayout_11 = QtGui.QFormLayout(self.scrollAreaWidgetContents_4)
        self.formLayout_11.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_11.setObjectName(_fromUtf8("formLayout_11"))
        self.sampleTypeLabel = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.sampleTypeLabel.setText(QtGui.QApplication.translate("MainWindow", "Sample Type", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleTypeLabel.setObjectName(_fromUtf8("sampleTypeLabel"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.LabelRole, self.sampleTypeLabel)
        self.file_samp_type = QtGui.QComboBox(self.scrollAreaWidgetContents_4)
        self.file_samp_type.setObjectName(_fromUtf8("file_samp_type"))
        self.file_samp_type.addItem(_fromUtf8(""))
        self.file_samp_type.setItemText(0, QtGui.QApplication.translate("MainWindow", "complex", None, QtGui.QApplication.UnicodeUTF8))
        self.file_samp_type.addItem(_fromUtf8(""))
        self.file_samp_type.setItemText(1, QtGui.QApplication.translate("MainWindow", "float", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.FieldRole, self.file_samp_type)
        self.fileLabel = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.fileLabel.setText(QtGui.QApplication.translate("MainWindow", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLabel.setObjectName(_fromUtf8("fileLabel"))
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.LabelRole, self.fileLabel)
        self.file_file_to_open = QtGui.QLineEdit(self.scrollAreaWidgetContents_4)
        self.file_file_to_open.setObjectName(_fromUtf8("file_file_to_open"))
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.FieldRole, self.file_file_to_open)
        self.recordingSampleRateSpsLabel = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.recordingSampleRateSpsLabel.setText(QtGui.QApplication.translate("MainWindow", "Recording Sample Rate (sps)", None, QtGui.QApplication.UnicodeUTF8))
        self.recordingSampleRateSpsLabel.setObjectName(_fromUtf8("recordingSampleRateSpsLabel"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.LabelRole, self.recordingSampleRateSpsLabel)
        self.file_rec_samp_rate = QtGui.QLineEdit(self.scrollAreaWidgetContents_4)
        self.file_rec_samp_rate.setObjectName(_fromUtf8("file_rec_samp_rate"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.FieldRole, self.file_rec_samp_rate)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_5.addWidget(self.scrollArea_4)
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_10)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.scrollArea_3 = QtGui.QScrollArea(self.tab_10)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_3.setPalette(palette)
        self.scrollArea_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 357, 161))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.formLayout_10 = QtGui.QFormLayout(self.scrollAreaWidgetContents_3)
        self.formLayout_10.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.sampleTypeLabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.sampleTypeLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Sample Type", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleTypeLabel_2.setObjectName(_fromUtf8("sampleTypeLabel_2"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.sampleTypeLabel_2)
        self.uhd_samp_type = QtGui.QComboBox(self.scrollAreaWidgetContents_3)
        self.uhd_samp_type.setObjectName(_fromUtf8("uhd_samp_type"))
        self.uhd_samp_type.addItem(_fromUtf8(""))
        self.uhd_samp_type.setItemText(0, QtGui.QApplication.translate("MainWindow", "complex", None, QtGui.QApplication.UnicodeUTF8))
        self.uhd_samp_type.addItem(_fromUtf8(""))
        self.uhd_samp_type.setItemText(1, QtGui.QApplication.translate("MainWindow", "float", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.uhd_samp_type)
        self.numberOfSamplesLabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.numberOfSamplesLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Gain (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfSamplesLabel_2.setObjectName(_fromUtf8("numberOfSamplesLabel_2"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.LabelRole, self.numberOfSamplesLabel_2)
        self.uhd_gain = QtGui.QSpinBox(self.scrollAreaWidgetContents_3)
        self.uhd_gain.setObjectName(_fromUtf8("uhd_gain"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.FieldRole, self.uhd_gain)
        self.uhd_samp_rate_label = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.uhd_samp_rate_label.setText(QtGui.QApplication.translate("MainWindow", "Sample Rate (sps)", None, QtGui.QApplication.UnicodeUTF8))
        self.uhd_samp_rate_label.setObjectName(_fromUtf8("uhd_samp_rate_label"))
        self.formLayout_10.setWidget(3, QtGui.QFormLayout.LabelRole, self.uhd_samp_rate_label)
        self.fileLabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.fileLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Antenna", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLabel_2.setObjectName(_fromUtf8("fileLabel_2"))
        self.formLayout_10.setWidget(4, QtGui.QFormLayout.LabelRole, self.fileLabel_2)
        self.uhd_ant = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.uhd_ant.setObjectName(_fromUtf8("uhd_ant"))
        self.formLayout_10.setWidget(4, QtGui.QFormLayout.FieldRole, self.uhd_ant)
        self.subdeviceSpecificationLabel = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.subdeviceSpecificationLabel.setText(QtGui.QApplication.translate("MainWindow", "Subdevice Specification", None, QtGui.QApplication.UnicodeUTF8))
        self.subdeviceSpecificationLabel.setObjectName(_fromUtf8("subdeviceSpecificationLabel"))
        self.formLayout_10.setWidget(5, QtGui.QFormLayout.LabelRole, self.subdeviceSpecificationLabel)
        self.uhd_subdev_spec = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.uhd_subdev_spec.setObjectName(_fromUtf8("uhd_subdev_spec"))
        self.formLayout_10.setWidget(5, QtGui.QFormLayout.FieldRole, self.uhd_subdev_spec)
        self.uhd_board_num_labell = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.uhd_board_num_labell.setText(QtGui.QApplication.translate("MainWindow", "Board Number", None, QtGui.QApplication.UnicodeUTF8))
        self.uhd_board_num_labell.setObjectName(_fromUtf8("uhd_board_num_labell"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.uhd_board_num_labell)
        self.uhd_board_num = QtGui.QSpinBox(self.scrollAreaWidgetContents_3)
        self.uhd_board_num.setObjectName(_fromUtf8("uhd_board_num"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.uhd_board_num)
        self.uhd_samp_rate = QtGui.QSpinBox(self.scrollAreaWidgetContents_3)
        self.uhd_samp_rate.setMaximum(999999999)
        self.uhd_samp_rate.setObjectName(_fromUtf8("uhd_samp_rate"))
        self.formLayout_10.setWidget(3, QtGui.QFormLayout.FieldRole, self.uhd_samp_rate)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.addWidget(self.scrollArea_3)
        self.tabWidget_2.addTab(self.tab_10, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.gridGroupBox_2)
        self.line = QtGui.QFrame(self.frame_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.gridGroupBox_21 = QtGui.QGroupBox(self.frame_2)
        self.gridGroupBox_21.setTitle(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.gridGroupBox_21.setObjectName(_fromUtf8("gridGroupBox_21"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridGroupBox_21)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.inputLabel = QtGui.QLabel(self.gridGroupBox_21)
        self.inputLabel.setText(QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.inputLabel.setObjectName(_fromUtf8("inputLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.inputLabel)
        self.input_selector = QtGui.QComboBox(self.gridGroupBox_21)
        self.input_selector.setObjectName(_fromUtf8("input_selector"))
        self.input_selector.addItem(_fromUtf8(""))
        self.input_selector.setItemText(0, QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.input_selector.addItem(_fromUtf8(""))
        self.input_selector.setItemText(1, QtGui.QApplication.translate("MainWindow", "UHD", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.input_selector)
        self.label_3 = QtGui.QLabel(self.gridGroupBox_21)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.method_selector = QtGui.QComboBox(self.gridGroupBox_21)
        self.method_selector.setEditable(False)
        self.method_selector.setObjectName(_fromUtf8("method_selector"))
        self.method_selector.addItem(_fromUtf8(""))
        self.method_selector.setItemText(0, QtGui.QApplication.translate("MainWindow", "Welch", None, QtGui.QApplication.UnicodeUTF8))
        self.method_selector.addItem(_fromUtf8(""))
        self.method_selector.setItemText(1, QtGui.QApplication.translate("MainWindow", "Welch (SP)", None, QtGui.QApplication.UnicodeUTF8))
        self.method_selector.addItem(_fromUtf8(""))
        self.method_selector.setItemText(2, QtGui.QApplication.translate("MainWindow", "Burg", None, QtGui.QApplication.UnicodeUTF8))
        self.method_selector.addItem(_fromUtf8(""))
        self.method_selector.setItemText(3, QtGui.QApplication.translate("MainWindow", "fcov", None, QtGui.QApplication.UnicodeUTF8))
        self.method_selector.addItem(_fromUtf8(""))
        self.method_selector.setItemText(4, QtGui.QApplication.translate("MainWindow", "fmcov", None, QtGui.QApplication.UnicodeUTF8))
        self.method_selector.addItem(_fromUtf8(""))
        self.method_selector.setItemText(5, QtGui.QApplication.translate("MainWindow", "MTM", None, QtGui.QApplication.UnicodeUTF8))
        self.method_selector.addItem(_fromUtf8(""))
        self.method_selector.setItemText(6, QtGui.QApplication.translate("MainWindow", "Music", None, QtGui.QApplication.UnicodeUTF8))
        self.method_selector.addItem(_fromUtf8(""))
        self.method_selector.setItemText(7, QtGui.QApplication.translate("MainWindow", "Esprit", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.method_selector)
        self.label_4 = QtGui.QLabel(self.gridGroupBox_21)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Center Frequency (MHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.center_f = QwtCounter(self.gridGroupBox_21)
        self.center_f.setNumButtons(2)
        self.center_f.setProperty("basicstep", 0.1)
        self.center_f.setMaxValue(1000000.0)
        self.center_f.setProperty("value", 100.0)
        self.center_f.setObjectName(_fromUtf8("center_f"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.center_f)
        self.scaleLabel = QtGui.QLabel(self.gridGroupBox_21)
        self.scaleLabel.setText(QtGui.QApplication.translate("MainWindow", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel.setObjectName(_fromUtf8("scaleLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.scaleLabel)
        self.scale = QtGui.QComboBox(self.gridGroupBox_21)
        self.scale.setObjectName(_fromUtf8("scale"))
        self.scale.addItem(_fromUtf8(""))
        self.scale.setItemText(0, QtGui.QApplication.translate("MainWindow", "Logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.scale.addItem(_fromUtf8(""))
        self.scale.setItemText(1, QtGui.QApplication.translate("MainWindow", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.scale)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.run_button = QtGui.QPushButton(self.gridGroupBox_21)
        self.run_button.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.run_button.setObjectName(_fromUtf8("run_button"))
        self.horizontalLayout_2.addWidget(self.run_button)
        self.pause_button = QtGui.QPushButton(self.gridGroupBox_21)
        self.pause_button.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.pause_button.setObjectName(_fromUtf8("pause_button"))
        self.horizontalLayout_2.addWidget(self.pause_button)
        self.close_button = QtGui.QPushButton(self.gridGroupBox_21)
        self.close_button.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.horizontalLayout_2.addWidget(self.close_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.gridGroupBox_21)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.gridGroupBox_21)
        self.line_2 = QtGui.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalGroupBox_3 = QtGui.QGroupBox(self.frame_2)
        self.verticalGroupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Spectrum Estimation Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalGroupBox_3.setObjectName(_fromUtf8("verticalGroupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalGroupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.verticalGroupBox_3)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.scrollArea_5 = QtGui.QScrollArea(self.tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_5.setPalette(palette)
        self.scrollArea_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName(_fromUtf8("scrollArea_5"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 374, 155))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.formLayout_2 = QtGui.QFormLayout(self.scrollAreaWidgetContents_5)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.moviingAverageLengthLabel = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.moviingAverageLengthLabel.setText(QtGui.QApplication.translate("MainWindow", "Moving Average Length", None, QtGui.QApplication.UnicodeUTF8))
        self.moviingAverageLengthLabel.setObjectName(_fromUtf8("moviingAverageLengthLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.moviingAverageLengthLabel)
        self.welch_mov_avg = QtGui.QSpinBox(self.scrollAreaWidgetContents_5)
        self.welch_mov_avg.setMaximum(9999)
        self.welch_mov_avg.setObjectName(_fromUtf8("welch_mov_avg"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.welch_mov_avg)
        self.overlapLabel = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.overlapLabel.setText(QtGui.QApplication.translate("MainWindow", "Overlap", None, QtGui.QApplication.UnicodeUTF8))
        self.overlapLabel.setObjectName(_fromUtf8("overlapLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.overlapLabel)
        self.welch_overlap = QtGui.QSpinBox(self.scrollAreaWidgetContents_5)
        self.welch_overlap.setMinimum(-1)
        self.welch_overlap.setMaximum(32765)
        self.welch_overlap.setObjectName(_fromUtf8("welch_overlap"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.welch_overlap)
        self.welch_win = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.welch_win.setText(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_win.setObjectName(_fromUtf8("welch_win"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.welch_win)
        self.welch_window = QtGui.QComboBox(self.scrollAreaWidgetContents_5)
        self.welch_window.setObjectName(_fromUtf8("welch_window"))
        self.welch_window.addItem(_fromUtf8(""))
        self.welch_window.setItemText(0, QtGui.QApplication.translate("MainWindow", "Hann", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_window.addItem(_fromUtf8(""))
        self.welch_window.setItemText(1, QtGui.QApplication.translate("MainWindow", "Hamming", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_window.addItem(_fromUtf8(""))
        self.welch_window.setItemText(2, QtGui.QApplication.translate("MainWindow", "Kaiser", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_window.addItem(_fromUtf8(""))
        self.welch_window.setItemText(3, QtGui.QApplication.translate("MainWindow", "Blackman", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_window.addItem(_fromUtf8(""))
        self.welch_window.setItemText(4, QtGui.QApplication.translate("MainWindow", "Blackman-Harris", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_window.addItem(_fromUtf8(""))
        self.welch_window.setItemText(5, QtGui.QApplication.translate("MainWindow", "Rectangular", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.welch_window)
        self.windowOptionLabel = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.windowOptionLabel.setText(QtGui.QApplication.translate("MainWindow", "Window-Option", None, QtGui.QApplication.UnicodeUTF8))
        self.windowOptionLabel.setObjectName(_fromUtf8("windowOptionLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.windowOptionLabel)
        self.welch_window_option = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_5)
        self.welch_window_option.setObjectName(_fromUtf8("welch_window_option"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.welch_window_option)
        self.fFTSizeLabel = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.fFTSizeLabel.setText(QtGui.QApplication.translate("MainWindow", "FFT-Size", None, QtGui.QApplication.UnicodeUTF8))
        self.fFTSizeLabel.setObjectName(_fromUtf8("fFTSizeLabel"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.fFTSizeLabel)
        self.welch_fft_size = QtGui.QComboBox(self.scrollAreaWidgetContents_5)
        self.welch_fft_size.setObjectName(_fromUtf8("welch_fft_size"))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(0, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(1, QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(2, QtGui.QApplication.translate("MainWindow", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(3, QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(4, QtGui.QApplication.translate("MainWindow", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(5, QtGui.QApplication.translate("MainWindow", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(6, QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(7, QtGui.QApplication.translate("MainWindow", "2048", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(8, QtGui.QApplication.translate("MainWindow", "4096", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(9, QtGui.QApplication.translate("MainWindow", "8192", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(10, QtGui.QApplication.translate("MainWindow", "16384", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(11, QtGui.QApplication.translate("MainWindow", "32768", None, QtGui.QApplication.UnicodeUTF8))
        self.welch_fft_size.addItem(_fromUtf8(""))
        self.welch_fft_size.setItemText(12, QtGui.QApplication.translate("MainWindow", "65536", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.welch_fft_size)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_10.addWidget(self.scrollArea_5)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_welchsp = QtGui.QWidget()
        self.tab_welchsp.setObjectName(_fromUtf8("tab_welchsp"))
        self.welchsp_window_option = QtGui.QDoubleSpinBox(self.tab_welchsp)
        self.welchsp_window_option.setGeometry(QtCore.QRect(124, 83, 53, 22))
        self.welchsp_window_option.setObjectName(_fromUtf8("welchsp_window_option"))
        self.welchsp_overlap = QtGui.QSpinBox(self.tab_welchsp)
        self.welchsp_overlap.setGeometry(QtCore.QRect(124, 30, 56, 22))
        self.welchsp_overlap.setMinimum(-1)
        self.welchsp_overlap.setMaximum(32765)
        self.welchsp_overlap.setObjectName(_fromUtf8("welchsp_overlap"))
        self.welchsp_window = QtGui.QComboBox(self.tab_welchsp)
        self.welchsp_window.setGeometry(QtCore.QRect(124, 56, 116, 23))
        self.welchsp_window.setObjectName(_fromUtf8("welchsp_window"))
        self.welchsp_window.addItem(_fromUtf8(""))
        self.welchsp_window.setItemText(0, QtGui.QApplication.translate("MainWindow", "Hann", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_window.addItem(_fromUtf8(""))
        self.welchsp_window.setItemText(1, QtGui.QApplication.translate("MainWindow", "Hamming", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_window.addItem(_fromUtf8(""))
        self.welchsp_window.setItemText(2, QtGui.QApplication.translate("MainWindow", "Kaiser", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_window.addItem(_fromUtf8(""))
        self.welchsp_window.setItemText(3, QtGui.QApplication.translate("MainWindow", "Blackman", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_window.addItem(_fromUtf8(""))
        self.welchsp_window.setItemText(4, QtGui.QApplication.translate("MainWindow", "Blackman-Harris", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_window.addItem(_fromUtf8(""))
        self.welchsp_window.setItemText(5, QtGui.QApplication.translate("MainWindow", "Rectangular", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_win = QtGui.QLabel(self.tab_welchsp)
        self.welchsp_win.setGeometry(QtCore.QRect(81, 56, 38, 23))
        self.welchsp_win.setText(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_win.setObjectName(_fromUtf8("welchsp_win"))
        self.fFTSizeLabel_7 = QtGui.QLabel(self.tab_welchsp)
        self.fFTSizeLabel_7.setGeometry(QtCore.QRect(79, 109, 40, 23))
        self.fFTSizeLabel_7.setText(QtGui.QApplication.translate("MainWindow", "FFT-Size", None, QtGui.QApplication.UnicodeUTF8))
        self.fFTSizeLabel_7.setObjectName(_fromUtf8("fFTSizeLabel_7"))
        self.welchsp_alpha = QtGui.QDoubleSpinBox(self.tab_welchsp)
        self.welchsp_alpha.setGeometry(QtCore.QRect(124, 4, 50, 22))
        self.welchsp_alpha.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.welchsp_alpha.setMinimum(0.01)
        self.welchsp_alpha.setMaximum(1.0)
        self.welchsp_alpha.setSingleStep(0.01)
        self.welchsp_alpha.setProperty("value", 0.1)
        self.welchsp_alpha.setObjectName(_fromUtf8("welchsp_alpha"))
        self.overlapLabel_2 = QtGui.QLabel(self.tab_welchsp)
        self.overlapLabel_2.setGeometry(QtCore.QRect(81, 30, 38, 22))
        self.overlapLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Overlap", None, QtGui.QApplication.UnicodeUTF8))
        self.overlapLabel_2.setObjectName(_fromUtf8("overlapLabel_2"))
        self.windowOptionLabel_2 = QtGui.QLabel(self.tab_welchsp)
        self.windowOptionLabel_2.setGeometry(QtCore.QRect(41, 83, 78, 22))
        self.windowOptionLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Window-Option", None, QtGui.QApplication.UnicodeUTF8))
        self.windowOptionLabel_2.setObjectName(_fromUtf8("windowOptionLabel_2"))
        self.moviingAverageLengthLabel_2 = QtGui.QLabel(self.tab_welchsp)
        self.moviingAverageLengthLabel_2.setGeometry(QtCore.QRect(40, 4, 81, 22))
        self.moviingAverageLengthLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Averaging Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.moviingAverageLengthLabel_2.setObjectName(_fromUtf8("moviingAverageLengthLabel_2"))
        self.welchsp_fft_size = QtGui.QComboBox(self.tab_welchsp)
        self.welchsp_fft_size.setGeometry(QtCore.QRect(124, 109, 64, 23))
        self.welchsp_fft_size.setObjectName(_fromUtf8("welchsp_fft_size"))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(0, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(1, QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(2, QtGui.QApplication.translate("MainWindow", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(3, QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(4, QtGui.QApplication.translate("MainWindow", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(5, QtGui.QApplication.translate("MainWindow", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(6, QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(7, QtGui.QApplication.translate("MainWindow", "2048", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(8, QtGui.QApplication.translate("MainWindow", "4096", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(9, QtGui.QApplication.translate("MainWindow", "8192", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(10, QtGui.QApplication.translate("MainWindow", "16384", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(11, QtGui.QApplication.translate("MainWindow", "32768", None, QtGui.QApplication.UnicodeUTF8))
        self.welchsp_fft_size.addItem(_fromUtf8(""))
        self.welchsp_fft_size.setItemText(12, QtGui.QApplication.translate("MainWindow", "65536", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.addTab(self.tab_welchsp, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.scrollArea_6 = QtGui.QScrollArea(self.tab_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_6.setPalette(palette)
        self.scrollArea_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName(_fromUtf8("scrollArea_6"))
        self.scrollAreaWidgetContents_6 = QtGui.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 374, 155))
        self.scrollAreaWidgetContents_6.setObjectName(_fromUtf8("scrollAreaWidgetContents_6"))
        self.formLayout_3 = QtGui.QFormLayout(self.scrollAreaWidgetContents_6)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.orderLabel = QtGui.QLabel(self.scrollAreaWidgetContents_6)
        self.orderLabel.setText(QtGui.QApplication.translate("MainWindow", "Order", None, QtGui.QApplication.UnicodeUTF8))
        self.orderLabel.setObjectName(_fromUtf8("orderLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.orderLabel)
        self.burg_order = QtGui.QSpinBox(self.scrollAreaWidgetContents_6)
        self.burg_order.setMinimum(2)
        self.burg_order.setMaximum(9999)
        self.burg_order.setObjectName(_fromUtf8("burg_order"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.burg_order)
        self.fFTSizeLabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_6)
        self.fFTSizeLabel_2.setText(QtGui.QApplication.translate("MainWindow", "FFT-Size", None, QtGui.QApplication.UnicodeUTF8))
        self.fFTSizeLabel_2.setObjectName(_fromUtf8("fFTSizeLabel_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.fFTSizeLabel_2)
        self.burg_fft_size = QtGui.QComboBox(self.scrollAreaWidgetContents_6)
        self.burg_fft_size.setObjectName(_fromUtf8("burg_fft_size"))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(0, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(1, QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(2, QtGui.QApplication.translate("MainWindow", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(3, QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(4, QtGui.QApplication.translate("MainWindow", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(5, QtGui.QApplication.translate("MainWindow", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(6, QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(7, QtGui.QApplication.translate("MainWindow", "2048", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(8, QtGui.QApplication.translate("MainWindow", "4096", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(9, QtGui.QApplication.translate("MainWindow", "8192", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(10, QtGui.QApplication.translate("MainWindow", "16384", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(11, QtGui.QApplication.translate("MainWindow", "32768", None, QtGui.QApplication.UnicodeUTF8))
        self.burg_fft_size.addItem(_fromUtf8(""))
        self.burg_fft_size.setItemText(12, QtGui.QApplication.translate("MainWindow", "65536", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.burg_fft_size)
        self.blockLengthLabel = QtGui.QLabel(self.scrollAreaWidgetContents_6)
        self.blockLengthLabel.setText(QtGui.QApplication.translate("MainWindow", "Block Length", None, QtGui.QApplication.UnicodeUTF8))
        self.blockLengthLabel.setObjectName(_fromUtf8("blockLengthLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.blockLengthLabel)
        self.burg_block_len = QtGui.QSpinBox(self.scrollAreaWidgetContents_6)
        self.burg_block_len.setMinimum(4)
        self.burg_block_len.setMaximum(65536)
        self.burg_block_len.setObjectName(_fromUtf8("burg_block_len"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.burg_block_len)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_11.addWidget(self.scrollArea_6)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.scrollArea_7 = QtGui.QScrollArea(self.tab_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_7.setPalette(palette)
        self.scrollArea_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName(_fromUtf8("scrollArea_7"))
        self.scrollAreaWidgetContents_7 = QtGui.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 374, 155))
        self.scrollAreaWidgetContents_7.setObjectName(_fromUtf8("scrollAreaWidgetContents_7"))
        self.formLayout_4 = QtGui.QFormLayout(self.scrollAreaWidgetContents_7)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.orderLabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        self.orderLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Order", None, QtGui.QApplication.UnicodeUTF8))
        self.orderLabel_2.setObjectName(_fromUtf8("orderLabel_2"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.orderLabel_2)
        self.fcov_order = QtGui.QSpinBox(self.scrollAreaWidgetContents_7)
        self.fcov_order.setMinimum(2)
        self.fcov_order.setMaximum(9999)
        self.fcov_order.setObjectName(_fromUtf8("fcov_order"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.fcov_order)
        self.fFTSizeLabel_3 = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        self.fFTSizeLabel_3.setText(QtGui.QApplication.translate("MainWindow", "FFT-Size", None, QtGui.QApplication.UnicodeUTF8))
        self.fFTSizeLabel_3.setObjectName(_fromUtf8("fFTSizeLabel_3"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.fFTSizeLabel_3)
        self.fcov_fft_size = QtGui.QComboBox(self.scrollAreaWidgetContents_7)
        self.fcov_fft_size.setObjectName(_fromUtf8("fcov_fft_size"))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(0, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(1, QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(2, QtGui.QApplication.translate("MainWindow", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(3, QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(4, QtGui.QApplication.translate("MainWindow", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(5, QtGui.QApplication.translate("MainWindow", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(6, QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(7, QtGui.QApplication.translate("MainWindow", "2048", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(8, QtGui.QApplication.translate("MainWindow", "4096", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(9, QtGui.QApplication.translate("MainWindow", "8192", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(10, QtGui.QApplication.translate("MainWindow", "16384", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(11, QtGui.QApplication.translate("MainWindow", "32768", None, QtGui.QApplication.UnicodeUTF8))
        self.fcov_fft_size.addItem(_fromUtf8(""))
        self.fcov_fft_size.setItemText(12, QtGui.QApplication.translate("MainWindow", "65536", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.fcov_fft_size)
        self.blockLengthLabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        self.blockLengthLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Block Length", None, QtGui.QApplication.UnicodeUTF8))
        self.blockLengthLabel_2.setObjectName(_fromUtf8("blockLengthLabel_2"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.blockLengthLabel_2)
        self.fcov_block_len = QtGui.QSpinBox(self.scrollAreaWidgetContents_7)
        self.fcov_block_len.setMinimum(4)
        self.fcov_block_len.setMaximum(65536)
        self.fcov_block_len.setObjectName(_fromUtf8("fcov_block_len"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.fcov_block_len)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_12.addWidget(self.scrollArea_7)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.scrollArea_8 = QtGui.QScrollArea(self.tab_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_8.setPalette(palette)
        self.scrollArea_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName(_fromUtf8("scrollArea_8"))
        self.scrollAreaWidgetContents_8 = QtGui.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 374, 155))
        self.scrollAreaWidgetContents_8.setObjectName(_fromUtf8("scrollAreaWidgetContents_8"))
        self.formLayout_5 = QtGui.QFormLayout(self.scrollAreaWidgetContents_8)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.orderLabel_3 = QtGui.QLabel(self.scrollAreaWidgetContents_8)
        self.orderLabel_3.setText(QtGui.QApplication.translate("MainWindow", "Order", None, QtGui.QApplication.UnicodeUTF8))
        self.orderLabel_3.setObjectName(_fromUtf8("orderLabel_3"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.orderLabel_3)
        self.fmcov_order = QtGui.QSpinBox(self.scrollAreaWidgetContents_8)
        self.fmcov_order.setMinimum(2)
        self.fmcov_order.setMaximum(9999)
        self.fmcov_order.setObjectName(_fromUtf8("fmcov_order"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.fmcov_order)
        self.fFTSizeLabel_4 = QtGui.QLabel(self.scrollAreaWidgetContents_8)
        self.fFTSizeLabel_4.setText(QtGui.QApplication.translate("MainWindow", "FFT-Size", None, QtGui.QApplication.UnicodeUTF8))
        self.fFTSizeLabel_4.setObjectName(_fromUtf8("fFTSizeLabel_4"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.fFTSizeLabel_4)
        self.fmcov_fft_size = QtGui.QComboBox(self.scrollAreaWidgetContents_8)
        self.fmcov_fft_size.setObjectName(_fromUtf8("fmcov_fft_size"))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(0, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(1, QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(2, QtGui.QApplication.translate("MainWindow", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(3, QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(4, QtGui.QApplication.translate("MainWindow", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(5, QtGui.QApplication.translate("MainWindow", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(6, QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(7, QtGui.QApplication.translate("MainWindow", "2048", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(8, QtGui.QApplication.translate("MainWindow", "4096", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(9, QtGui.QApplication.translate("MainWindow", "8192", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(10, QtGui.QApplication.translate("MainWindow", "16384", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(11, QtGui.QApplication.translate("MainWindow", "32768", None, QtGui.QApplication.UnicodeUTF8))
        self.fmcov_fft_size.addItem(_fromUtf8(""))
        self.fmcov_fft_size.setItemText(12, QtGui.QApplication.translate("MainWindow", "65536", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.fmcov_fft_size)
        self.blockLengthLabel_3 = QtGui.QLabel(self.scrollAreaWidgetContents_8)
        self.blockLengthLabel_3.setText(QtGui.QApplication.translate("MainWindow", "Block Length", None, QtGui.QApplication.UnicodeUTF8))
        self.blockLengthLabel_3.setObjectName(_fromUtf8("blockLengthLabel_3"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.blockLengthLabel_3)
        self.fmcov_block_len = QtGui.QSpinBox(self.scrollAreaWidgetContents_8)
        self.fmcov_block_len.setMinimum(4)
        self.fmcov_block_len.setMaximum(65536)
        self.fmcov_block_len.setObjectName(_fromUtf8("fmcov_block_len"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.fmcov_block_len)
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_8)
        self.verticalLayout_13.addWidget(self.scrollArea_8)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.scrollArea_9 = QtGui.QScrollArea(self.tab_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_9.setPalette(palette)
        self.scrollArea_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_9.setWidgetResizable(True)
        self.scrollArea_9.setObjectName(_fromUtf8("scrollArea_9"))
        self.scrollAreaWidgetContents_9 = QtGui.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 374, 155))
        self.scrollAreaWidgetContents_9.setObjectName(_fromUtf8("scrollAreaWidgetContents_9"))
        self.formLayout_6 = QtGui.QFormLayout(self.scrollAreaWidgetContents_9)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.timeBandwithProductLabel = QtGui.QLabel(self.scrollAreaWidgetContents_9)
        self.timeBandwithProductLabel.setText(QtGui.QApplication.translate("MainWindow", "Time-Bandwith Product", None, QtGui.QApplication.UnicodeUTF8))
        self.timeBandwithProductLabel.setObjectName(_fromUtf8("timeBandwithProductLabel"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.timeBandwithProductLabel)
        self.numberOfTapersLabel = QtGui.QLabel(self.scrollAreaWidgetContents_9)
        self.numberOfTapersLabel.setText(QtGui.QApplication.translate("MainWindow", "Number of Tapers", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfTapersLabel.setObjectName(_fromUtf8("numberOfTapersLabel"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.numberOfTapersLabel)
        self.mtm_num_tap = QtGui.QSpinBox(self.scrollAreaWidgetContents_9)
        self.mtm_num_tap.setMaximum(999)
        self.mtm_num_tap.setObjectName(_fromUtf8("mtm_num_tap"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.mtm_num_tap)
        self.weightMethodLabel = QtGui.QLabel(self.scrollAreaWidgetContents_9)
        self.weightMethodLabel.setText(QtGui.QApplication.translate("MainWindow", "Weight Method", None, QtGui.QApplication.UnicodeUTF8))
        self.weightMethodLabel.setObjectName(_fromUtf8("weightMethodLabel"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.weightMethodLabel)
        self.mtm_weight_method = QtGui.QComboBox(self.scrollAreaWidgetContents_9)
        self.mtm_weight_method.setObjectName(_fromUtf8("mtm_weight_method"))
        self.mtm_weight_method.addItem(_fromUtf8(""))
        self.mtm_weight_method.setItemText(0, QtGui.QApplication.translate("MainWindow", "unity", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_weight_method.addItem(_fromUtf8(""))
        self.mtm_weight_method.setItemText(1, QtGui.QApplication.translate("MainWindow", "eigenvalues", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_weight_method.addItem(_fromUtf8(""))
        self.mtm_weight_method.setItemText(2, QtGui.QApplication.translate("MainWindow", "adaptive", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.mtm_weight_method)
        self.dPSSLengthLabel = QtGui.QLabel(self.scrollAreaWidgetContents_9)
        self.dPSSLengthLabel.setText(QtGui.QApplication.translate("MainWindow", "DPSS Length", None, QtGui.QApplication.UnicodeUTF8))
        self.dPSSLengthLabel.setObjectName(_fromUtf8("dPSSLengthLabel"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.dPSSLengthLabel)
        self.mtm_tbp = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_9)
        self.mtm_tbp.setObjectName(_fromUtf8("mtm_tbp"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.mtm_tbp)
        self.mtm_dpss_len = QtGui.QComboBox(self.scrollAreaWidgetContents_9)
        self.mtm_dpss_len.setObjectName(_fromUtf8("mtm_dpss_len"))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(0, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(1, QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(2, QtGui.QApplication.translate("MainWindow", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(3, QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(4, QtGui.QApplication.translate("MainWindow", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(5, QtGui.QApplication.translate("MainWindow", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(6, QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(7, QtGui.QApplication.translate("MainWindow", "2048", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(8, QtGui.QApplication.translate("MainWindow", "4096", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(9, QtGui.QApplication.translate("MainWindow", "8192", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(10, QtGui.QApplication.translate("MainWindow", "16384", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(11, QtGui.QApplication.translate("MainWindow", "32768", None, QtGui.QApplication.UnicodeUTF8))
        self.mtm_dpss_len.addItem(_fromUtf8(""))
        self.mtm_dpss_len.setItemText(12, QtGui.QApplication.translate("MainWindow", "65536", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.mtm_dpss_len)
        self.scrollArea_9.setWidget(self.scrollAreaWidgetContents_9)
        self.verticalLayout_14.addWidget(self.scrollArea_9)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.scrollArea_10 = QtGui.QScrollArea(self.tab_6)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_10.setPalette(palette)
        self.scrollArea_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_10.setWidgetResizable(True)
        self.scrollArea_10.setObjectName(_fromUtf8("scrollArea_10"))
        self.scrollAreaWidgetContents_10 = QtGui.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 374, 155))
        self.scrollAreaWidgetContents_10.setObjectName(_fromUtf8("scrollAreaWidgetContents_10"))
        self.formLayout_7 = QtGui.QFormLayout(self.scrollAreaWidgetContents_10)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.correlationSizeLabel = QtGui.QLabel(self.scrollAreaWidgetContents_10)
        self.correlationSizeLabel.setText(QtGui.QApplication.translate("MainWindow", "Correlation Size", None, QtGui.QApplication.UnicodeUTF8))
        self.correlationSizeLabel.setObjectName(_fromUtf8("correlationSizeLabel"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.correlationSizeLabel)
        self.music_cor_size = QtGui.QSpinBox(self.scrollAreaWidgetContents_10)
        self.music_cor_size.setMaximum(9999)
        self.music_cor_size.setObjectName(_fromUtf8("music_cor_size"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.music_cor_size)
        self.sinusoidsCountLabel = QtGui.QLabel(self.scrollAreaWidgetContents_10)
        self.sinusoidsCountLabel.setText(QtGui.QApplication.translate("MainWindow", "Sinusoids Count", None, QtGui.QApplication.UnicodeUTF8))
        self.sinusoidsCountLabel.setObjectName(_fromUtf8("sinusoidsCountLabel"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.sinusoidsCountLabel)
        self.music_sin_cnt = QtGui.QSpinBox(self.scrollAreaWidgetContents_10)
        self.music_sin_cnt.setMaximum(9999)
        self.music_sin_cnt.setObjectName(_fromUtf8("music_sin_cnt"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.music_sin_cnt)
        self.fFTSizeLabel_5 = QtGui.QLabel(self.scrollAreaWidgetContents_10)
        self.fFTSizeLabel_5.setText(QtGui.QApplication.translate("MainWindow", "FFT-Size", None, QtGui.QApplication.UnicodeUTF8))
        self.fFTSizeLabel_5.setObjectName(_fromUtf8("fFTSizeLabel_5"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.fFTSizeLabel_5)
        self.music_fft_size = QtGui.QComboBox(self.scrollAreaWidgetContents_10)
        self.music_fft_size.setObjectName(_fromUtf8("music_fft_size"))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(0, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(1, QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(2, QtGui.QApplication.translate("MainWindow", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(3, QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(4, QtGui.QApplication.translate("MainWindow", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(5, QtGui.QApplication.translate("MainWindow", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(6, QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(7, QtGui.QApplication.translate("MainWindow", "2048", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(8, QtGui.QApplication.translate("MainWindow", "4096", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(9, QtGui.QApplication.translate("MainWindow", "8192", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(10, QtGui.QApplication.translate("MainWindow", "16384", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(11, QtGui.QApplication.translate("MainWindow", "32768", None, QtGui.QApplication.UnicodeUTF8))
        self.music_fft_size.addItem(_fromUtf8(""))
        self.music_fft_size.setItemText(12, QtGui.QApplication.translate("MainWindow", "65536", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.music_fft_size)
        self.scrollArea_10.setWidget(self.scrollAreaWidgetContents_10)
        self.verticalLayout_15.addWidget(self.scrollArea_10)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.scrollArea_11 = QtGui.QScrollArea(self.tab_7)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_11.setPalette(palette)
        self.scrollArea_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_11.setWidgetResizable(True)
        self.scrollArea_11.setObjectName(_fromUtf8("scrollArea_11"))
        self.scrollAreaWidgetContents_11 = QtGui.QWidget()
        self.scrollAreaWidgetContents_11.setGeometry(QtCore.QRect(0, 0, 374, 155))
        self.scrollAreaWidgetContents_11.setObjectName(_fromUtf8("scrollAreaWidgetContents_11"))
        self.formLayout_8 = QtGui.QFormLayout(self.scrollAreaWidgetContents_11)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.correlationSizeLabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_11)
        self.correlationSizeLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Correlation Size", None, QtGui.QApplication.UnicodeUTF8))
        self.correlationSizeLabel_2.setObjectName(_fromUtf8("correlationSizeLabel_2"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.correlationSizeLabel_2)
        self.esprit_cor_size = QtGui.QSpinBox(self.scrollAreaWidgetContents_11)
        self.esprit_cor_size.setMaximum(9999)
        self.esprit_cor_size.setObjectName(_fromUtf8("esprit_cor_size"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.esprit_cor_size)
        self.sinusoidsCountLabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_11)
        self.sinusoidsCountLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Sinusoids Count", None, QtGui.QApplication.UnicodeUTF8))
        self.sinusoidsCountLabel_2.setObjectName(_fromUtf8("sinusoidsCountLabel_2"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.sinusoidsCountLabel_2)
        self.esprit_sin_cnt = QtGui.QSpinBox(self.scrollAreaWidgetContents_11)
        self.esprit_sin_cnt.setMaximum(999)
        self.esprit_sin_cnt.setObjectName(_fromUtf8("esprit_sin_cnt"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.esprit_sin_cnt)
        self.fFTSizeLabel_6 = QtGui.QLabel(self.scrollAreaWidgetContents_11)
        self.fFTSizeLabel_6.setText(QtGui.QApplication.translate("MainWindow", "FFT-Size", None, QtGui.QApplication.UnicodeUTF8))
        self.fFTSizeLabel_6.setObjectName(_fromUtf8("fFTSizeLabel_6"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.fFTSizeLabel_6)
        self.esprit_fft_size = QtGui.QComboBox(self.scrollAreaWidgetContents_11)
        self.esprit_fft_size.setObjectName(_fromUtf8("esprit_fft_size"))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(0, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(1, QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(2, QtGui.QApplication.translate("MainWindow", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(3, QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(4, QtGui.QApplication.translate("MainWindow", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(5, QtGui.QApplication.translate("MainWindow", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(6, QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(7, QtGui.QApplication.translate("MainWindow", "2048", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(8, QtGui.QApplication.translate("MainWindow", "4096", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(9, QtGui.QApplication.translate("MainWindow", "8192", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(10, QtGui.QApplication.translate("MainWindow", "16384", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(11, QtGui.QApplication.translate("MainWindow", "32768", None, QtGui.QApplication.UnicodeUTF8))
        self.esprit_fft_size.addItem(_fromUtf8(""))
        self.esprit_fft_size.setItemText(12, QtGui.QApplication.translate("MainWindow", "65536", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.esprit_fft_size)
        self.scrollArea_11.setWidget(self.scrollAreaWidgetContents_11)
        self.verticalLayout_16.addWidget(self.scrollArea_11)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.verticalGroupBox_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1236, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Input Settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.close_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QtGui.QApplication.translate("MainWindow", "UHD", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Welch", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_welchsp), QtGui.QApplication.translate("MainWindow", "Welch (SP)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Burg", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "fcov", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "fmcov", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "MTM", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Music", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Esprit", None, QtGui.QApplication.UnicodeUTF8))

