SUBROUTINE ZMUSIC_SPECTRUM(SAMPLES, LSAMPLES, N, M, PSPECTRUM, LPSPECTRUM)
  IMPLICIT NONE
  INTEGER :: LSAMPLES, N, M, I, K, LPSPECTRUM, LWORK, INFO
  COMPLEX*16 ,ALLOCATABLE :: WORK(:)
  COMPLEX*16 :: SAMPLES(LSAMPLES), R(M,M), EV(N), G(M, M-N), A(M), RES(M)
  DOUBLE PRECISION :: PSPECTRUM(LPSPECTRUM)
  DOUBLE PRECISION :: PI, OMEGA, DELTA, W(M), RWORK(3*M-2), NORM, DZNRM2

  CALL ZCORREST(SAMPLES, LSAMPLES, M, R)

  ALLOCATE( WORK(1) )
  LWORK = -1
  CALL ZHEEV('V', 'L', M, R, M, W, WORK, LWORK, RWORK, INFO)
  LWORK = INT(WORK(1))
  DEALLOCATE (WORK)
  ALLOCATE( WORK(LWORK) )
  CALL ZHEEV('V', 'L', M, R, M, W, WORK, LWORK, RWORK, INFO)
  G = R(:, 1:M-N)
  DEALLOCATE (WORK)

  PI = 3.1415926535897932384626433832795028841971d0
  OMEGA = -PI
  DELTA = 2*PI/(LPSPECTRUM-1)
  DO I = 1, LPSPECTRUM
    DO K = 0, M-1
      A(K+1) = EXP((0, -1) * OMEGA  * K)
    END DO
    CALL ZGEMV('C', M, M-N, 1.0d0, G, M , A, 1, 0, RES, 1)
    NORM = DZNRM2(M, RES, 1)
    PSPECTRUM(I) = 1.0d0 / NORM
    OMEGA = OMEGA + DELTA
  END DO
END SUBROUTINE ZMUSIC_SPECTRUM
